### PR TITLE
turning in assignment

### PR DESCRIPTION
**Pull request by nicktrull**

### CODE REVIEW

**Comment by rtablada** [comment]
The styling and JS looks like it is coming along. The only thing missing is the ability to close the modal using the `X`

**Comment by nicktrull** [comment]
How do you mean missing? Everything is working on my end so I'm not sure why it would be missing on your end. Is it not even visible? When you open the modal there's a blue button up top that spans the text area. Triggers close when I click.

**Comment by rtablada** [comment]
apr 04 2016 07 43

**Comment by rtablada** [comment]
No button when I see it. Maybe something isn't committed and pushed?

**Comment by nicktrull** [comment]
@rtablada Yeah it looks like there were a lot of changes when I git add. Oops. Maybe it works now.

**Comment by nicktrull** [comment]
Since what you're looking were looking at I restyled my flexbox and made it super responsive. Also changed the modal to fit within all screens. And was in the process of trying to figure out the JS to click on a character and re render the page with that characters series. But it's a little tricky. Was able to get it to render the sidebar character but when I tried getting the characters to render things started breaking.

**Pull request merged**
